# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/const.ipynb

__all__ = ['CONCURRENCY_LIMIT', 'DATA_DIR', 'JACCARD_DEDUP_THRESHOLD', 'ONET_DIR', 'OUTPUT_DIR', 'TASK_CHUNK_SIZE', 'TASK_REFINE_MODEL', 'TECH_CHUNK_SIZE', 'TECH_FILTER_MODEL', 'TOOL_CHUNK_SIZE', 'TOOL_FILTER_MODEL', 'VALID_TASK_TYPES']

# %% nbs/const.ipynb 2
from pathlib import Path

# %% nbs/const.ipynb 4
DATA_DIR = Path(__file__).parent.parent / "_dev" / "00_data_download"
ONET_DIR = DATA_DIR / "onet_data" / "db_30_2_text"
OUTPUT_DIR = DATA_DIR.parent.parent / "data" / "uk_onet"

# %% nbs/const.ipynb 6
TECH_FILTER_MODEL = "gpt-5-mini"
TOOL_FILTER_MODEL = "gpt-5-mini"
TASK_REFINE_MODEL = "gpt-5-mini"
CONCURRENCY_LIMIT = 10

# %% nbs/const.ipynb 8
TECH_CHUNK_SIZE = 400
TOOL_CHUNK_SIZE = 200
TASK_CHUNK_SIZE = 150
JACCARD_DEDUP_THRESHOLD = 0.85

# %% nbs/const.ipynb 10
VALID_TASK_TYPES = {'Core', 'Supplemental', 'Unclassified'}
